services:
  namenode:
    build: 
      context: .
      dockerfile: .docker/namenode.Dockerfile
    container_name: namenode
    hostname: namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./namenode:/opt/hadoop/data/nameNode
      - ./config:/opt/hadoop/etc/hadoop
      - ./start-hdfs.sh:/start-hdfs.sh
      - ./config/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties
      - ./config/krb5.conf:/etc/krb5.conf
      - ./secrets:/etc/security/keytabs
    ports:
      - "9870:9870"
      - "8088:8088"
    command: [ "/bin/bash", "/start-hdfs.sh" ]
    networks:
      hdfs_network:
        ipv4_address: 172.30.0.2

  datanode1:
    build: 
      context: .
      dockerfile: .docker/datanode.Dockerfile
    container_name: datanode1
    hostname: datanode1
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./datanode1:/opt/hadoop/data/dataNode
      - ./config:/opt/hadoop/etc/hadoop
      - ./config/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties
      - ./config/krb5.conf:/etc/krb5.conf
      - ./secrets:/etc/security/keytabs
      - ./config/container-executor.cfg:/opt/hadoop/etc/hadoop/container-executor.cfg
    depends_on:
      - namenode
    networks:
      hdfs_network:
        ipv4_address: 172.30.0.3

  datanode2:
    build: 
      context: .
      dockerfile: .docker/datanode.Dockerfile
    container_name: datanode2
    hostname: datanode2
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    volumes:
      - ./datanode2:/opt/hadoop/data/dataNode
      - ./config:/opt/hadoop/etc/hadoop
      - ./config/log4j.properties:/opt/hadoop/etc/hadoop/log4j.properties
      - ./config/krb5.conf:/etc/krb5.conf
      - ./secrets:/etc/security/keytabs
      - ./config/container-executor.cfg:/opt/hadoop/etc/hadoop/container-executor.cfg
    depends_on:
      - namenode
    networks:
      hdfs_network:
        ipv4_address: 172.30.0.4
  kdc:
    build: 
      context: .
      dockerfile: .docker/kdc.Dockerfile
    container_name: kdc
    hostname: kdc
    command: [ "/bin/bash", "/init-kdc.sh" ]
    user: root
    ports:
      - "88:88"
      - "749:749"
    volumes:
      - ./config/krb5.conf:/etc/krb5.conf
      - ./secrets:/var/kerberos/krb5kdc/secrets
      - ./init-kdc.sh:/init-kdc.sh
    networks:
      hdfs_network:
        ipv4_address: 172.30.0.5

networks:
  hdfs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24